networks:
  didi-students: 
    driver: bridge
services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - didi-students
    volumes:
      - postgres:/var/lib/postgresql/data
  node_app: 
    container_name: node_app
    build: .
    ports:
    - 5000:5000
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - didi-students
volumes:
  postgres: